export type { JsonObject, JsonPrimitive, JsonValue } from './types.js';
export { GENERATED_PATHS } from './generated.js';
export { defineConfig } from './define-config.js';
export type { ToolingDefineConfigInput } from './define-config.js';
export { domSetup } from './dom-setup.js';
export { toolingPlugin } from './tooling-plugin.js';
export type { ToolingPluginOptions } from './tooling-plugin.js';
export { lint } from './lint.js';
export type { LintOptions, LintOverride, LintTarget, ScopedTarget } from './lint.js';
export { DEFAULT_FMT_IGNORES, fmt } from './fmt.js';
export type { FmtOptions } from './fmt.js';
export { staged } from './staged.js';
export type { StagedOptions } from './staged.js';
export { pack } from './pack.js';
export type { PackOptions } from './pack.js';
export { testNode, testProjects, testReact } from './vitest.js';
export type { TestProjectsOptions, VitestEnvironment, VitestProjectOptions } from './vitest.js';
export { viteReactApp } from './vite.js';
export type { ViteReactAppOptions } from './vite.js';
